[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/easystore-webhook"
  to = "/.netlify/functions/easystore-webhook"
  status = 200
  force = true

[[redirects]]
  from = "/api/easystore-push"
  to = "/.netlify/functions/easystore-push"
  status = 200
  force = true

[[redirects]]
  from = "/api/tiktok-oauth"
  to = "/.netlify/functions/tiktok-oauth"
  status = 200
  force = true

[[redirects]]
  from = "/api/tiktok-sync"
  to = "/.netlify/functions/tiktok-sync"
  status = 200
  force = true

[[redirects]]
  from = "/api/tiktok-stock-sync"
  to = "/.netlify/functions/tiktok-stock-sync"
  status = 200
  force = true

[[redirects]]
  from = "/api/tiktok-product-sync"
  to = "/.netlify/functions/tiktok-product-sync"
  status = 200
  force = true

[[redirects]]
  from = "/api/shopee-auth-link"
  to = "/.netlify/functions/shopee-auth-link"
  status = 200
  force = true

[[redirects]]
  from = "/api/shopee-oauth"
  to = "/.netlify/functions/shopee-oauth"
  status = 200
  force = true
